import Head from 'next/head';
import { Inter } from '@next/font/google';
import Link from 'next/link';
import {getSession, useSession, signOut } from "next-auth/react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const[session, setSession] = useState(true);
  const {data:session}= useSession();
  function handleSignOut(){
    signOut();
  }
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {session ? User({session,handleSignOut}):Guest()}
    </>
  )
}

//Guest 
// function Guest(){
const Guest = () => {
  return(
    <main className="container mx-auto text-center py-20">
        <h3 className="text-4xl font-bold underline">
          Guest Home Page
        </h3>
        <div className='flex justify-center'>
          <Link href={'/login'} className='mt-5 px-10 py-1 rounded-sm bg-indigo-500'>Sign In</Link>
        </div>
      </main>
  )
}
//Authorize User
const User = ({session,handleSignOut}) => {
  return(
    <main className="container mx-auto text-center py-20">
        <h3 className="text-4xl font-bold underline">
          Authorize User Home Page
        </h3>
        <div className='details'>
          <h5>{session.user.name}</h5>
          <h5>{session.user.email}</h5>
        </div>
        <div className="flex justfy-center">
          <button onClick={handleSignOut} className='mt-5 px-10 py-1 rounded-sm bg-indigo-500 bg-gray-50'>Sign Out</button>
        </div>
        <div className='flex justify-center'>
          <Link href={'/profile'} className='mt-5 px-10 py-1 rounded-sm bg-indigo-500'>Profile Page</Link>
        </div>
      </main>
  )
}

export async function getServerSideProps({req}){
  const session = await getSession({req})
  if(!session){
    return{
      redirect:{
        destination:'/login',
        permanent:false
      }
    }
  }
  return{
    props:{session}
  }
}
